# Generated by Django 2.1.5 on 2019-02-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('auth_id', models.CharField(max_length=100)),
                ('lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('status', models.CharField(max_length=100)),
                ('friends', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='friends_list', to='checkn_app.User')),
            ],
        ),
    ]
