# Generated by Django 2.1.5 on 2019-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='users',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='users', to='checkn_app.AppUser'),
        ),
    ]
