# Generated by Django 2.1.5 on 2019-02-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkn_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='name',
        ),
    ]
