# Generated by Django 2.1.5 on 2019-02-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkn_app', '0002_remove_appuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
