# Generated by Django 2.1.5 on 2019-02-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkn_app', '0002_auto_20190221_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
