# Generated by Django 2.1.5 on 2019-02-27 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkn_app', '0002_place_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='users',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='place',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_list', to='checkn_app.Place'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='status',
            field=models.CharField(blank='true', default='', max_length=100),
        ),
    ]
