# Generated by Django 2.1.5 on 2019-02-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkn_app', '0008_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, default=1, null=True, related_name='_user_friends_+', to='checkn_app.User'),
        ),
    ]
