# Generated by Django 2.1.5 on 2019-02-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkn_app', '0010_auto_20190221_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='place',
        ),
    ]
