# Generated by Django 2.1.5 on 2019-02-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkn_app', '0011_auto_20190221_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, default=1, null=True, related_name='_user_friends_+', to='checkn_app.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='place_name', to='checkn_app.Place'),
        ),
    ]
