# Generated by Django 2.1.5 on 2019-02-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkn_app', '0013_auto_20190221_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, default=1, related_name='_user_friends_+', to='checkn_app.User'),
        ),
    ]
